let myReceipt = [];
console.log(myReceipt);
myReceipt.push('yam');
console.log(myReceipt);
myReceipt.push('bread');
console.log(myReceipt);
myReceipt.push('garri');
console.log(myReceipt);
myReceipt.pop();
console.log(myReceipt);
myReceipt.shift();
console.log(myReceipt);
myReceipt.unshift('garri');
console.log(myReceipt);